version: '3'
services:
  web:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/app:/usr/share/nginx/html
  
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: on-failure